(ns acme.compile-cljs
  (:require [c3kit.scaffold.cljs :as cljs]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn prerender-ns? [content]
  (boolean (re-find #"defmethod\s+\S*prerender\?\s+:(?!default\b)\S+\s+\[\S*\]" content)))

(defn extract-ns [content]
  (second (re-find #"\(ns\s+([\w.*+!\-'?/$=<>&]+)" content)))

(defn find-prerender-namespaces [source-dirs]
  (->> source-dirs
       (map io/file)
       (mapcat file-seq)
       (filter #(re-find #"\.(cljs|cljc)$" (.getName %)))
       (filter #(prerender-ns? (slurp %)))
       (map #(extract-ns (slurp %)))
       (remove nil?)
       sort
       vec))

(defn generate-prerender-requires!
  ([namespaces] (generate-prerender-requires! namespaces "dev/acme/ssr/prerender_pages.cljs"))
  ([namespaces output-path]
   (.mkdirs (.getParentFile (io/file output-path)))
   (let [requires (str/join "\n            " (map #(str "[" % "]") (sort namespaces)))]
     (spit output-path
           (str ";; Auto-generated by acme.compile-cljs — do not edit\n"
                "(ns acme.ssr.prerender-pages\n"
                "  (:require " requires "))\n")))))

(defn- patch-prerender! []
  (let [f (io/file "resources/prerender/prerender.js")]
    (when (.exists f)
      (let [preamble (slurp (io/file "dev/acme/ssr/prerender_preamble.js"))
            content  (slurp f)
            patched  (-> content
                         (str/replace "#!/usr/bin/env node\n" "")
                         (str/replace "\"object\"===typeof exports&&\"undefined\"!==typeof module"
                                      "false")
                         (str/replace "})(this,function(" "})(globalThis,function("))]
        (spit f (str "#!/usr/bin/env node\n" preamble "\n" patched))))))

(defn -main [& args]
  (let [original-env (System/getProperty "acme.env")]
    (try
      (System/setProperty "acme.env" "prerender")
      (generate-prerender-requires! (find-prerender-namespaces ["src/cljc" "src/cljs"]))
      (cljs/-main "once")
      (patch-prerender!)
      (finally
        (if original-env
          (System/setProperty "acme.env" original-env)
          (System/clearProperty "acme.env")))))
  (apply cljs/-main args))
